Repository blue-stream/blue-stream-video, pull requests merged in 2019-03, with the labels that each got.

#37 Add sysadmin
  src/video/video.aggregator.ts
  src/video/video.contoller.ts
  src/video/video.manager.spec.ts
  src/video/video.manager.ts
  src/video/video.repository.spec.ts
  src/video/video.repository.ts
  src/view/view.manager.ts
Labels: enhancement

#38 feat: add more query params to getVideos
  package.json
  src/video/video.contoller.ts
  src/video/video.manager.ts
  src/video/video.repository.ts
Labels: bug, enhancement

#40 fix: fix get classified videos
  src/video/video.repository.ts
Labels: bug

#42 Fix classification last update duplicates
  src/classification/last-update/classification-last-update.model.ts
  src/classification/last-update/classification-last-update.spec.ts
  src/classification/last-update/classification-last-update.ts
Labels: bug
